version: 2

defaults: &defaults
  docker:
    - image: circleci/node:10-stretch

workflows:
  version: 2
  build_and_test:
    jobs:
      - checkout
      - install_dependencies:
          requires:
            - checkout
      - lint:
          requires:
            - install_dependencies
      - build:
          requires:
            - install_dependencies
      - test:
          requires:
            - install_dependencies

jobs:
  checkout:
    <<: *defaults
    steps:
      - restore_cache:
          keys:
            - asseter-config-{{ .Branch }}-{{ .Revision }}
            - asseter-config-{{ .Branch }}
            - asseter-config
      - checkout
      - save_cache:
          key: asseter-config-{{ .Branch }}-{{ .Revision }}
          paths:
            - .git
      - persist_to_workspace:
          root: .
          paths: .

  install_dependencies:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - asseter-config-dependencies-{{ checksum "yarn.lock" }}
            - asseter-config-dependencies
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          key: asseter-config-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: .
          paths:
            - node_modules

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Linting
          command: yarn lint --format junit --out lint-results.xml
      - store_test_results:
          path: lint-results.xml

  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build
          command: yarn version

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Tests
          command: yarn test --ci --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT: test-results.xml
      - store_test_results:
          path: test-results.xml
